# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-20 01:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': '商品类别表',
                'db_table': 'shop_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShopColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('value', models.ImageField(upload_to='color/')),
            ],
            options={
                'verbose_name': '商品颜色',
                'db_table': 'shop_color',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShopGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gname', models.CharField(max_length=255)),
                ('gdesc', models.CharField(blank=True, max_length=1024, null=True)),
                ('gprice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('goldprice', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': '商品',
                'db_table': 'shop_goods',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShopGoodsdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': '商品展示图片',
                'db_table': 'shop_goodsdetails',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShopOrder',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('desc', models.IntegerField()),
                ('created', models.DateTimeField()),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name': '商品订单',
                'db_table': 'shop_order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShopSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': '尺码表',
                'db_table': 'shop_size',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShopStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
            ],
            options={
                'verbose_name': '购物商店',
                'db_table': 'shop_store',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShopStoreSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '商品尺寸表',
                'db_table': 'shop_store_size',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShopUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=254)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': '用户表',
                'db_table': 'shop_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodsid', models.IntegerField()),
                ('colorid', models.IntegerField()),
                ('sizeid', models.IntegerField()),
                ('count', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mallproject.ShopUser')),
            ],
        ),
    ]
